name: Generate ascii

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: executing shell script
              run: | 
               chmod +x asciiscript.sh
               ./asciiscript.sh                           #path of shell script
            
            
            